### MTA Simulator walkthrough

This notebook provides a walkthrough of using the `boardings` class to get data and estimates for onboards and offboards at Bedford Av on the L train.

In [12]:
import src.boardings as boardings 

boardings.init()

print(boardings.get_ordered_stops("L", 0))

{'Canarsie-Rockaway Pkwy': 138, 'East 105 St': 137, 'New Lots Av': 136, 'Livonia Av': 135, 'Sutter Av': 134, 'Atlantic Av': 133, 'Broadway Junction': 621, 'Bushwick Av-Aberdeen St': 131, 'Wilson Av': 130, 'Halsey St': 129, 'Myrtle-Wyckoff Avs': 630, 'DeKalb Av': 127, 'Jefferson St': 126, 'Morgan Av': 125, 'Montrose Av': 124, 'Grand St': 123, 'Graham Av': 122, 'Lorimer St': 629, 'Bedford Av': 120, '1 Av': 119, '3 Av': 118, '14 St-Union Sq': 602, '6 Av': 601, '8 Av': 618}

Getting data from the socrata api:

In [8]:

df_onboards_120 = boardings.get_onboards_data("120") # Bedford Av
df_onboards_120.head(5)

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,1,Monday,13,120,Bedford Av (L),602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",80.9367
1,2025,1,Monday,14,120,Bedford Av (L),602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",73.4673
2,2025,1,Monday,14,120,Bedford Av (L),119,1 Av (L),59.9783
3,2025,1,Monday,15,120,Bedford Av (L),119,1 Av (L),57.4603
4,2025,1,Monday,13,120,Bedford Av (L),119,1 Av (L),49.5998

Calculating onboards and offboards:

In [9]:
complex_id = "120"
line = "L"
direction = 1 # 0 = north/east-bound (towards 8 Av), 1 = south/west-bound (towards Rockaway)

year = 2025
month = 9
day_of_week = "Monday"
hour_of_day = "9"

# Get weekday ridership for May 2024 at 9am from station 623
df_onboards = boardings.get_onboards_data(complex_id, year, month, day_of_week, hour_of_day)
df_offboards = boardings.get_offboards_data(complex_id, year, month, day_of_week, hour_of_day)


obs_onboard, df_onboard = boardings.get_onboardings (complex_id, line, direction, df_onboards)
obs_offboard, df_offboard = boardings.get_offboardings (complex_id, line, direction, df_offboards)

Printing the results:

In [10]:
print("Total Onboardings: ", obs_onboard)

df_onboard.head(10)

Total Onboardings:  244.10822577386776

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Monday,9,120,Bedford Av (L),611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",17.693750
1,2025,9,Monday,9,120,Bedford Av (L),164,"34 St-Penn Station (A,C,E)",34.281800
2,2025,9,Monday,9,120,Bedford Av (L),628,"Fulton St (A,C,J,Z,2,3,4,5)",11.151250
3,2025,9,Monday,9,120,Bedford Av (L),623,"Canal St (J,N,Q,R,W,Z,6)",17.383600
4,2025,9,Monday,9,120,Bedford Av (L),168,"Spring St (C,E)",9.553800
5,2025,9,Monday,9,120,Bedford Av (L),624,"Chambers St (A,C)/WTC (E)/Park Pl (2,3)/Cortla...",4.572300
6,2025,9,Monday,9,120,Bedford Av (L),614,"59 St-Columbus Circle (A,B,C,D,1)",4.721267
7,2025,9,Monday,9,120,Bedford Av (L),165,"23 St (C,E)",6.496700
8,2025,9,Monday,9,120,Bedford Av (L),167,"W 4 St-Wash Sq (A,C,E,B,D,F,M)",4.107000
9,2025,9,Monday,9,120,Bedford Av (L),622,"Brooklyn Bridge-City Hall (4,5,6)/Chambers St ...",6.133300

In [11]:
print("Total Offboardings: ", obs_offboard)

df_offboard.head(10)

Total Offboardings:  674.4989386212357

,year,month,day_of_week,hour_of_day,origin_station_complex_id,origin_station_complex_name,destination_station_complex_id,destination_station_complex_name,estimated_average_ridership
0,2025,9,Monday,9,119,1 Av (L),120,Bedford Av (L),66.8378
1,2025,9,Monday,9,601,"14 St (F,M,1,2,3)/6 Av (L)",120,Bedford Av (L),42.8444
2,2025,9,Monday,9,611,"Times Sq-42 St (N,Q,R,W,S,1,2,3,7)/42 St (A,C,E)",120,Bedford Av (L),27.4827
3,2025,9,Monday,9,602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",120,Bedford Av (L),29.7414
4,2025,9,Monday,9,618,"14 St (A,C,E)/8 Av (L)",120,Bedford Av (L),27.0496
5,2025,9,Monday,9,164,"34 St-Penn Station (A,C,E)",120,Bedford Av (L),13.4097
6,2025,9,Monday,9,610,"Grand Central-42 St (S,4,5,6,7)",120,Bedford Av (L),25.4570
7,2025,9,Monday,9,118,3 Av (L),120,Bedford Av (L),21.7106
8,2025,9,Monday,9,612,"Lexington Av-53 St (E,M)/51 St (6)",120,Bedford Av (L),8.4116
9,2025,9,Monday,9,151,"145 St (A,C,B,D)",120,Bedford Av (L),4.0501